'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources

    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()> _
    Friend Module Resources

        Private resourceMan As Global.System.Resources.ResourceManager

        Private resourceCulture As Global.System.Globalization.CultureInfo

        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ARIA_Premium_System.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = Value
            End Set
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property AppIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("AppIcon", resourceCulture)
                Return CType(obj, System.Drawing.Icon)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap similar to (Bitmap).
        '''</summary>
        Friend ReadOnly Property LogoImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogoImage", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap similar to (Bitmap).
        '''</summary>
        Friend ReadOnly Property MicrophoneIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MicrophoneIcon", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap similar to (Bitmap).
        '''</summary>
        Friend ReadOnly Property RecordingIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RecordingIcon", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap similar to (Bitmap).
        '''</summary>
        Friend ReadOnly Property SettingsIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SettingsIcon", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap similar to (Bitmap).
        '''</summary>
        Friend ReadOnly Property WaveformBackground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WaveformBackground", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to ARIA Premium System v1.0
        '''
        '''  Advanced voice recognition and meeting management system with AI-powered transcription.
        '''
        '''  Features:
        '''  • Real-time voice transcription
        '''  • Multi-provider AI support (OpenAI, Azure, Google)
        '''  • Meeting recording and management
        '''  • Cost tracking and monitoring
        '''  • Dark/Light theme support
        '''  • Secure API key management
        '''
        '''  Copyright © 2024 ARIA Technologies
        '''  All rights reserved.
        '''</summary>
        Friend ReadOnly Property AboutText() As String
            Get
                Return ResourceManager.GetString("AboutText", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Meeting recording started successfully..
        '''</summary>
        Friend ReadOnly Property RecordingStartedMessage() As String
            Get
                Return ResourceManager.GetString("RecordingStartedMessage", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Meeting recording stopped and saved..
        '''</summary>
        Friend ReadOnly Property RecordingStoppedMessage() As String
            Get
                Return ResourceManager.GetString("RecordingStoppedMessage", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Configuration saved successfully..
        '''</summary>
        Friend ReadOnly Property SettingsSavedMessage() As String
            Get
                Return ResourceManager.GetString("SettingsSavedMessage", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Please enter a valid API key..
        '''</summary>
        Friend ReadOnly Property InvalidApiKeyMessage() As String
            Get
                Return ResourceManager.GetString("InvalidApiKeyMessage", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Voice engine initialized successfully..
        '''</summary>
        Friend ReadOnly Property VoiceEngineReadyMessage() As String
            Get
                Return ResourceManager.GetString("VoiceEngineReadyMessage", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Error connecting to voice service..
        '''</summary>
        Friend ReadOnly Property VoiceEngineErrorMessage() As String
            Get
                Return ResourceManager.GetString("VoiceEngineErrorMessage", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Meeting exported successfully..
        '''</summary>
        Friend ReadOnly Property MeetingExportedMessage() As String
            Get
                Return ResourceManager.GetString("MeetingExportedMessage", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Cost limit reached! Please review your usage..
        '''</summary>
        Friend ReadOnly Property CostLimitReachedMessage() As String
            Get
                Return ResourceManager.GetString("CostLimitReachedMessage", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Network connection lost. Please check your internet connection..
        '''</summary>
        Friend ReadOnly Property NetworkErrorMessage() As String
            Get
                Return ResourceManager.GetString("NetworkErrorMessage", resourceCulture)
            End Get
        End Property

    End Module
End Namespace