'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"), _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
Partial Friend NotInheritable Class MySettings
    Inherits Global.System.Configuration.ApplicationSettingsBase

    Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()), MySettings)

#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region

    Public Shared ReadOnly Property [Default]() As MySettings
        Get

#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("True")> _
    Public Property UseDarkTheme() As Boolean
        Get
            Return CType(Me("UseDarkTheme"), Boolean)
        End Get
        Set
            Me("UseDarkTheme") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("Azure")> _
    Public Property VoiceProvider() As String
        Get
            Return CType(Me("VoiceProvider"), String)
        End Get
        Set
            Me("VoiceProvider") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("en-US")> _
    Public Property VoiceLanguage() As String
        Get
            Return CType(Me("VoiceLanguage"), String)
        End Get
        Set
            Me("VoiceLanguage") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("Female")> _
    Public Property VoiceGender() As String
        Get
            Return CType(Me("VoiceGender"), String)
        End Get
        Set
            Me("VoiceGender") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("50")> _
    Public Property VoiceSpeed() As Integer
        Get
            Return CType(Me("VoiceSpeed"), Integer)
        End Get
        Set
            Me("VoiceSpeed") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("50")> _
    Public Property VoicePitch() As Integer
        Get
            Return CType(Me("VoicePitch"), Integer)
        End Get
        Set
            Me("VoicePitch") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("False")> _
    Public Property ContinuousListening() As Boolean
        Get
            Return CType(Me("ContinuousListening"), Boolean)
        End Get
        Set
            Me("ContinuousListening") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("True")> _
    Public Property VoiceActivation() As Boolean
        Get
            Return CType(Me("VoiceActivation"), Boolean)
        End Get
        Set
            Me("VoiceActivation") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("Default")> _
    Public Property AudioDevice() As String
        Get
            Return CType(Me("AudioDevice"), String)
        End Get
        Set
            Me("AudioDevice") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("WAV")> _
    Public Property RecordingFormat() As String
        Get
            Return CType(Me("RecordingFormat"), String)
        End Get
        Set
            Me("RecordingFormat") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("44100")> _
    Public Property SampleRate() As String
        Get
            Return CType(Me("SampleRate"), String)
        End Get
        Set
            Me("SampleRate") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("True")> _
    Public Property AutoSave() As Boolean
        Get
            Return CType(Me("AutoSave"), Boolean)
        End Get
        Set
            Me("AutoSave") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("False")> _
    Public Property BackgroundRecording() As Boolean
        Get
            Return CType(Me("BackgroundRecording"), Boolean)
        End Get
        Set
            Me("BackgroundRecording") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("")> _
    Public Property SaveLocation() As String
        Get
            Return CType(Me("SaveLocation"), String)
        End Get
        Set
            Me("SaveLocation") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("False")> _
    Public Property StartWithWindows() As Boolean
        Get
            Return CType(Me("StartWithWindows"), Boolean)
        End Get
        Set
            Me("StartWithWindows") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("True")> _
    Public Property MinimizeToTray() As Boolean
        Get
            Return CType(Me("MinimizeToTray"), Boolean)
        End Get
        Set
            Me("MinimizeToTray") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("True")> _
    Public Property EnableLogging() As Boolean
        Get
            Return CType(Me("EnableLogging"), Boolean)
        End Get
        Set
            Me("EnableLogging") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("Info")> _
    Public Property LogLevel() As String
        Get
            Return CType(Me("LogLevel"), String)
        End Get
        Set
            Me("LogLevel") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("True")> _
    Public Property AutoUpdate() As Boolean
        Get
            Return CType(Me("AutoUpdate"), Boolean)
        End Get
        Set
            Me("AutoUpdate") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("True")> _
    Public Property EnableCostTracking() As Boolean
        Get
            Return CType(Me("EnableCostTracking"), Boolean)
        End Get
        Set
            Me("EnableCostTracking") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("10.00")> _
    Public Property CostLimit() As Decimal
        Get
            Return CType(Me("CostLimit"), Decimal)
        End Get
        Set
            Me("CostLimit") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("True")> _
    Public Property CostAlerts() As Boolean
        Get
            Return CType(Me("CostAlerts"), Boolean)
        End Get
        Set
            Me("CostAlerts") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("5.00")> _
    Public Property CostAlertThreshold() As Decimal
        Get
            Return CType(Me("CostAlertThreshold"), Decimal)
        End Get
        Set
            Me("CostAlertThreshold") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("")> _
    Public Property OpenAIApiKey() As String
        Get
            Return CType(Me("OpenAIApiKey"), String)
        End Get
        Set
            Me("OpenAIApiKey") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("")> _
    Public Property AzureApiKey() As String
        Get
            Return CType(Me("AzureApiKey"), String)
        End Get
        Set
            Me("AzureApiKey") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("")> _
    Public Property GoogleApiKey() As String
        Get
            Return CType(Me("GoogleApiKey"), String)
        End Get
        Set
            Me("GoogleApiKey") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("")> _
    Public Property AzureEndpoint() As String
        Get
            Return CType(Me("AzureEndpoint"), String)
        End Get
        Set
            Me("AzureEndpoint") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("")> _
    Public Property AzureRegion() As String
        Get
            Return CType(Me("AzureRegion"), String)
        End Get
        Set
            Me("AzureRegion") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("1200, 700")> _
    Public Property MainFormSize() As System.Drawing.Size
        Get
            Return CType(Me("MainFormSize"), System.Drawing.Size)
        End Get
        Set
            Me("MainFormSize") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("CenterScreen")> _
    Public Property MainFormLocation() As String
        Get
            Return CType(Me("MainFormLocation"), String)
        End Get
        Set
            Me("MainFormLocation") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("Normal")> _
    Public Property MainFormWindowState() As String
        Get
            Return CType(Me("MainFormWindowState"), String)
        End Get
        Set
            Me("MainFormWindowState") = Value
        End Set
    End Property

End Class